services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: symfony
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - php-net

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: "postgresql://symfony:password@database:5432/symfony_db?serverVersion=16&charset=utf8"
    networks:
      - php-net
      - nginx-net

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - nginx-net

volumes:
  db-data:


networks:
  nginx-net:
    driver: bridge
  php-net:
    driver: bridge
